[common]
server_addr = "47.118.16.173"
server_port = 7000

# 反向代理 - 通过tcp协议，访问服务器的8000端口，反向代理到Django的8000端口
[[proxies]]
name = "django"
type = "tcp"
# Docker网络中使用服务名访问Django容器
local_ip = "django"
local_port = 8000
remote_port = 8000
