# Generated by Django 5.2.6 on 2025-09-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitCommitAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_sha', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='提交标识码 (SHA)')),
                ('author_name', models.CharField(max_length=255, verbose_name='提交人')),
                ('commit_timestamp', models.DateTimeField(verbose_name='提交时间')),
                ('code_diff', models.TextField(verbose_name='提交的代码变更 (Diff)')),
                ('commit_message', models.TextField(verbose_name='提交注释')),
                ('analysis_suggestion', models.TextField(blank=True, null=True, verbose_name='AI修改意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='记录更新时间')),
            ],
            options={
                'verbose_name': 'Git提交分析记录',
                'verbose_name_plural': 'Git提交分析记录',
                'db_table': 'git_data',
                'ordering': ['-commit_timestamp'],
            },
        ),
    ]
