# Generated by Django 4.1 on 2025-09-19 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ai', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE git_data CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE git_data CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
    ]
