# Generated by Django 4.1 on 2025-09-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ai', '0002_auto_20250919_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitcommitanalysis',
            name='is_push',
            field=models.IntegerField(choices=[(0, '未推送'), (1, '已推送')], default=0, verbose_name='是否已推送到企业微信'),
        ),
    ]
