# Generated by Django 5.2.6 on 2025-09-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ai', '0003_gitcommitanalysis_is_push'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_owner', models.CharField(help_text='GitHub仓库的所有者用户名', max_length=255, verbose_name='仓库作者/所有者')),
                ('repo_name', models.CharField(help_text='GitHub仓库名称', max_length=255, verbose_name='仓库名称')),
                ('webhook_secret', models.CharField(help_text='GitHub Webhook的密钥，用于验证请求来源', max_length=255, verbose_name='Webhook密钥')),
                ('github_token', models.CharField(help_text='用于访问GitHub API的个人访问令牌', max_length=255, verbose_name='GitHub个人访问令牌')),
                ('is_enabled', models.BooleanField(default=True, help_text='是否启用此仓库的代码审查功能', verbose_name='是否启用')),
                ('wechat_webhook_url', models.URLField(blank=True, help_text='用于推送代码审查结果的企业微信群机器人Webhook地址', max_length=500, null=True, verbose_name='企业微信Webhook URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '仓库配置',
                'verbose_name_plural': '仓库配置',
                'db_table': 'repository_config',
                'ordering': ['-created_at'],
                'unique_together': {('repo_owner', 'repo_name')},
            },
        ),
        migrations.DeleteModel(
            name='GitCommitAnalysis',
        ),
    ]
