# Generated by Django 5.2.6 on 2025-10-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ai', '0004_repositoryconfig_delete_gitcommitanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryconfig',
            name='ollama_prompt_template',
            field=models.TextField(blank=True, help_text='用于代码审查的自定义提示词模板，支持变量替换。如果为空则使用系统默认提示词', null=True, verbose_name='Ollama模型提示词模板'),
        ),
    ]
