"""
Django settings for code_review project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from celery.schedules import crontab
from dotenv import load_dotenv

# 使用pymysql替代MySQLdb
import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Python 路径配置（已移除 simpleui）

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-2k=x9_t=1)sw*@#oabqe0*r34t*%goq95o^)$0*l_90rv4cb4*')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# 判断是否为生产环境
IS_PRODUCTION = not DEBUG

# 生产环境安全检查：强制要求安全的 SECRET_KEY
if IS_PRODUCTION and 'insecure' in SECRET_KEY:
    raise ValueError('⚠️ 生产环境必须设置安全的 SECRET_KEY 环境变量！请在 .env 文件中配置。')

# 代理和转发配置（根据环境自动切换）
if IS_PRODUCTION:
    # 生产环境：假设有 Nginx/Caddy 等反向代理
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    # 开发环境：直接访问，不需要代理头处理
    USE_X_FORWARDED_HOST = False
    USE_X_FORWARDED_PORT = False
    SECURE_PROXY_SSL_HEADER = None

# HTTPS 安全配置（根据环境自动切换）
if IS_PRODUCTION:
    SECURE_SSL_REDIRECT = True  # 生产环境：强制 HTTPS 重定向
    SECURE_HSTS_SECONDS = 31536000  # 1年
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    SECURE_SSL_REDIRECT = False  # 开发环境：不强制 HTTPS
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# ALLOWED_HOSTS 配置
if IS_PRODUCTION:
    # 生产环境：只允许配置的域名
    ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '47.118.16.173,www.wsztest.online').split(',')
else:
    # 开发环境：允许所有（方便本地开发和 ngrok 等工具）
    ALLOWED_HOSTS = ["*"]

# CSRF 和 Cookie 配置
CSRF_TRUSTED_ORIGINS = [
    # HTTP 地址（开发环境）
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://47.118.16.173:8000',
    'http://www.wsztest.online',
    
    # HTTPS 地址（生产环境）
    'https://localhost:8000',
    'https://127.0.0.1:8000',
    'https://47.118.16.173',
    'https://47.118.16.173:8000',
    'https://www.wsztest.online',
]

# ===== CSRF Cookie 安全配置（根据环境自动切换）=====
if IS_PRODUCTION:
    # 生产环境：严格安全模式
    CSRF_COOKIE_SECURE = True       # 仅通过 HTTPS 传输（防中间人攻击）
    CSRF_COOKIE_HTTPONLY = True     # 禁止 JavaScript 读取（防 XSS 攻击窃取 token）
    CSRF_COOKIE_SAMESITE = 'Strict' # 严格同站策略（最安全）
else:
    # 开发环境：宽松模式（方便开发调试）
    CSRF_COOKIE_SECURE = False      # 允许 HTTP 传输
    CSRF_COOKIE_HTTPONLY = False    # 允许 JavaScript 读取
    CSRF_COOKIE_SAMESITE = 'Lax'    # 宽松模式（兼容性好）

CSRF_USE_SESSIONS = False           # 使用 Cookie 存储（性能更好）
CSRF_COOKIE_NAME = 'csrftoken'      # Cookie 名称
CSRF_COOKIE_DOMAIN = None           # 自动使用当前域名
CSRF_COOKIE_AGE = 31449600          # 1年有效期

# ===== Session 会话配置（根据环境自动切换）=====
if IS_PRODUCTION:
    SESSION_COOKIE_SECURE = True    # 仅 HTTPS 传输
    SESSION_COOKIE_SAMESITE = 'Strict'  # 严格模式
else:
    SESSION_COOKIE_SECURE = False   # 允许 HTTP
    SESSION_COOKIE_SAMESITE = 'Lax' # 宽松模式

SESSION_COOKIE_HTTPONLY = True      # 始终禁止 JS 访问（防 XSS）
SESSION_COOKIE_AGE = 1209600        # 2周有效期

# ===== CORS 跨域配置（根据环境自动切换）=====
if IS_PRODUCTION:
    # 生产环境：严格限制允许的源
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        'https://47.118.16.173',
        'https://www.wsztest.online',
    ]
    CORS_ALLOW_CREDENTIALS = True   # 允许携带 Cookie
else:
    # 开发环境：允许所有源（方便前端开发）
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = False  # 不需要携带 Cookie（避免冲突）

CORS_ALLOW_HEADERS = list(__import__('corsheaders.defaults').defaults.default_headers) + [
    'x-csrftoken',  # 允许前端通过此 header 发送 CSRF token
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # CORS 跨域支持
    'django_celery_beat',  # Celery定时任务管理
    'app_ai',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'code_review.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'code_review.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.getenv('DB_NAME', 'code_review'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', '123456'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'  # 中文简体

TIME_ZONE = 'Asia/Shanghai'  # 中国时区 (UTC+8)

USE_I18N = True

USE_TZ = True  # 使用时区感知的 datetime（推荐）


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ===== Celery 配置 =====
# Celery Broker设置
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')

# Celery Result Backend设置
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

# Celery任务序列化
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# Celery时区设置
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Celery任务路由 - 已移除旧的tasks目录配置
CELERY_TASK_ROUTES = {
    # 所有任务使用默认队列
}

# Celery任务结果过期时间（秒）
CELERY_RESULT_EXPIRES = 3600  # 1小时

# Celery Worker配置
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000

# 使用线程池而不是进程池，避免HTTP连接问题
CELERY_WORKER_POOL = 'threads'
CELERY_WORKER_CONCURRENCY = 2

# Celery Beat调度器配置（用于定时任务）
# 使用数据库调度器，可以在Django Admin中管理定时任务
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# 定时任务配置 - 通过Django Admin管理
# CELERY_BEAT_SCHEDULE = {} # 留空，使用数据库调度器在Admin中配置

# 手动指定要导入的任务模块
CELERY_IMPORTS = [
    'app_ai.tasks.async_get',
    'app_ai.tasks.async_push',
]

# Celery任务失败重试配置
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True

# Celery日志配置
CELERY_WORKER_HIJACK_ROOT_LOGGER = False
CELERY_WORKER_LOG_FORMAT = '[%(asctime)s: %(levelname)s/%(processName)s] %(message)s'
CELERY_WORKER_TASK_LOG_FORMAT = '[%(asctime)s: %(levelname)s/%(processName)s][%(task_name)s(%(task_id)s)] %(message)s'

# ===== 日志配置 =====
import os as _log_os
# 确保日志目录存在
_LOG_DIR = BASE_DIR / 'logs'
_LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(_LOG_DIR / 'django.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'app_ai': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
